//! v2 BLE protocol — re-exports wire codec and translate layer.
pub use crate::wire::{
    decode_proto, encode_proto, parse_mac_address_bytes, STATION_CURRENT_TIME_CHARACTERISTIC_UUID,
    STATION_CURRENT_TIME_CHARACTERISTIC_UUID_16,
    STATION_EVENTS_CHARACTERISTIC_UUID, STATION_EVENTS_CHARACTERISTIC_UUID_16,
    STATION_MAC_ADDR_CHARACTERISTIC_UUID, STATION_MAC_ADDR_CHARACTERISTIC_UUID_16,
    STATION_PLANT_PROFILE_CHARACTERISTIC_UUID, STATION_PLANT_PROFILE_CHARACTERISTIC_UUID_16,
    STATION_SERVICE_UUID, STATION_SERVICE_UUID_16, STATION_SYNC_STATE_CHARACTERISTIC_UUID,
    STATION_SYNC_STATE_CHARACTERISTIC_UUID_16,
};